services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: klevert/hbsexpress:v1.0
    container_name: tesexpress
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
